string help_string[] = "\n"
                       "usage:\n"
                       "\n"
                       "bfish -i{interface} [-p] [-c] [-F{f_file}] [filter string]\n"
                       "\n"
                       "bfish -h\n"
                       "\n"
                       "\n"
                       "examples:\n"
                       "\n"
                       "bfish -itun0 -Ffilter1\n"
                       "\n"
                       "\n"
                       "options:\n"
                       "\n"
                       " -H  Hide specific frame/packet/datagram types\n"
                       "     el   - ethernet loopback\n"
                       "     cdp  - cisco discovery protocol\n"
                       "\n"
                       " -c  Count of first bytes that have to be catured for each packet\n"
                       "\n"
                       " -o  Output to file, filename given as parametr\n"
                       "\n"
                       " -O  Output to file only, no screen output, filename given as parametr\n"
                       "\n"
                       " -i  Interface, currently ethernet, tun and loopback are supported\n"
                       "\n"
                       " -p  Promisious mode off\n"
                       "\n"
                       " -F  Filter file, reads filter rule from given file\n"
                       "\n"
                       " -h  Displays this message ;)\n"
                       "\n\n";
